from .AdminSchema import AdminSchema
from .ClassGroupSchema import ClassGroupSchema
from .ClassSchedualeSchema import ClassSchedualSchema
from .DeptSchema import DeptSchema
from .GradeSchema import GradeSchema
from .LabGroupSchema import LabGroupSchema
from .LabSchedualeSchema import LabSchedualSchema
from .MaterialSchema import MaterialSchema
from .NotifisSchema import NotificationSchema
from .SchedualeSchema import SchedualeSchema
from .StudentSchema import StudentSchema
from .SupervisorSchema import SupervisorSchema
from .TeacherSchema import TeacherSchema
from .UserSchema import UserSchema