"""confirm ish.

Revision ID: 596401341836
Revises: 7590ee82965d
Create Date: 2021-02-05 00:33:20.644020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596401341836'
down_revision = '7590ee82965d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
