"""secondary.

Revision ID: a5fcc860b438
Revises: ae37adbbcb13
Create Date: 2020-12-06 19:53:41.333121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fcc860b438'
down_revision = 'ae37adbbcb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('c_type', sa.Integer(), nullable=True),
    sa.Column('dept', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('g_type', sa.Integer(), nullable=True),
    sa.Column('dept', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=5), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_scheduale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_group.id'], ),
    sa.ForeignKeyConstraint(['id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_scheduales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['lab_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_scheduales')
    op.drop_table('class_scheduale')
    op.drop_table('schedules')
    op.drop_table('lab_group')
    op.drop_table('class_group')
    # ### end Alembic commands ###
